### ISSUE TITLE
Eliminate render-blocking resources

### ISSUE THREAD

**Issue by improvethings** [wowthemesnet/jekyll-theme-memoirs#11]
Have you tried this theme on [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/)? 

The biggest issue appears to be "Eliminate render-blocking resources" (over 1 second) which is related to prism.css, theme.css, and jquery.min.js. Any suggestions how to resolve this so it's not showing up as red/the biggest issue? 

It also has "Avoid chaining critical requests 11 chains found". 

Thanks in advance!

**Comment by wowthemesnet** [comment]
Hi, @improvethings, If you're not using syntax highlighter you can remove prism.js and prism.css.
