### ISSUE TITLE
About Us page

### ISSUE THREAD

**Issue by reesericci** [wowthemesnet/jekyll-theme-memoirs#9]
I think there should be an "About Us" page introducing all the authors included in this amazing jekyll theme.

**Comment by reesericci** [comment]
Any response? @wowthemesnet

**Comment by innowebka** [comment]
> 
> 
> I think there should be an "About Us" page introducing all the authors included in this amazing jekyll theme.

you can do this on your own just add about us.md to _pages.

**Comment by reesericci** [comment]
I did, I just think it should be included. Something based off of the Author Box?

**Comment by mrsid-31** [comment]
If you want to have a ABOUT US for Authors then just create a new page dude.

**Comment by reesericci** [comment]
@mrsid-31 I did make one, all I am saying I think it should be included as part of this theme.  I think it would be a good addition to this theme.

**Comment by mrsid-31** [comment]
@reesericci Nice idea mate but I think they don't need to do so cz Authors Box is already present there which shows author details.

**Comment by reesericci** [comment]
I just have mine display the author box of all the authors on the page. I think something like that could make sense.

**Comment by reesericci** [comment]
@wowthemesnet can you weigh in?

**Comment by wowthemesnet** [comment]
Is this okay? https://wowthemesnet.github.io/jekyll-theme-memoirs/authors
